Repository jenkinsci/cloudbees-folder-plugin, pull requests merged in 2024-02, with the labels that each got.

#371 Typos
  src/main/resources/com/cloudbees/hudson/plugins/folder/AbstractFolder/tasks-new_de.properties
  src/main/resources/com/cloudbees/hudson/plugins/folder/Messages_de.properties
Labels: documentation

#375 Revert refactoring of `ChildNameGenerator`
  src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java
  src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolderDescriptor.java
  src/main/java/com/cloudbees/hudson/plugins/folder/ChildNameGenerator.java
  src/test/java/com/cloudbees/hudson/plugins/folder/FolderTest.java
Labels: bug

#376 [JENKINS-72613] ItemGroup.getItemName override & refactor, take 2
  src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java
  src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolderDescriptor.java
  src/main/java/com/cloudbees/hudson/plugins/folder/ChildNameGenerator.java
  src/test/java/com/cloudbees/hudson/plugins/folder/FolderTest.java
Labels: chore

#379 Assorted cleanups
  src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java
  src/main/java/com/cloudbees/hudson/plugins/folder/Folder.java
  src/main/java/com/cloudbees/hudson/plugins/folder/FolderProperty.java
  src/main/java/com/cloudbees/hudson/plugins/folder/FolderPropertyDescriptor.java
  src/main/java/com/cloudbees/hudson/plugins/folder/computed/DefaultOrphanedItemStrategy.java
  src/main/java/com/cloudbees/hudson/plugins/folder/computed/PeriodicFolderTrigger.java
  src/main/java/com/cloudbees/hudson/plugins/folder/relocate/StandardHandler.java
  src/main/java/com/cloudbees/hudson/plugins/folder/views/DefaultFolderViewHolder.java
  src/test/java/com/cloudbees/hudson/plugins/folder/FolderTest.java
  src/test/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProviderTest.java
Labels: chore
