Repository jenkinsci/cloudbees-folder-plugin, pull requests merged in 2024-01, with the labels that each got.

#356 Removing `AbstractFolder.delete` override
  pom.xml
  src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java
  src/main/resources/com/cloudbees/hudson/plugins/folder/Messages.properties
  src/main/resources/com/cloudbees/hudson/plugins/folder/Messages_de.properties
  src/main/resources/com/cloudbees/hudson/plugins/folder/Messages_fr.properties
  src/main/resources/com/cloudbees/hudson/plugins/folder/Messages_zh_CN.properties
  src/test/java/com/cloudbees/hudson/plugins/folder/FolderTest.java
Labels: dependencies

#365 Make `FolderComputation` implement `Loadable`
  src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java
  src/main/java/com/cloudbees/hudson/plugins/folder/computed/FolderComputation.java
Labels: developer

#366 [JENKINS-72611] Forbid updating credentials ID
  src/main/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProvider.java
  src/test/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProviderTest.java
Labels: bug

#368 Revert "[JENKINS-72611] Forbid updating credentials ID"
  src/main/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProvider.java
  src/test/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProviderTest.java
Labels: bug
