Repository jenkinsci/cloudbees-folder-plugin, pull requests merged in 2025-04, with the labels that each got.

#480 Drop support for migrating from `branch-api` 1.x to 2.x
  src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java
  src/main/java/com/cloudbees/hudson/plugins/folder/ChildNameGenerator.java
  src/test/java/com/cloudbees/hudson/plugins/folder/ChildNameGeneratorAltTest.java
  src/test/java/com/cloudbees/hudson/plugins/folder/ChildNameGeneratorRecTest.java
  src/test/java/com/cloudbees/hudson/plugins/folder/ChildNameGeneratorTest.java
  src/test/resources/com/cloudbees/hudson/plugins/folder/ChildNameGeneratorAltTest/upgrade.zip
  src/test/resources/com/cloudbees/hudson/plugins/folder/ChildNameGeneratorRecTest/upgrade.zip
  src/test/resources/com/cloudbees/hudson/plugins/folder/ChildNameGeneratorTest/upgrade.zip
  src/test/resources/com/cloudbees/hudson/plugins/folder/ChildNameGeneratorTest/upgradeNFD.zip
Labels: internal

#486 Retain child item identity when using a `NameMangler`
  src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java
  src/test/java/com/cloudbees/hudson/plugins/folder/ChildNameGeneratorAltTest.java
Labels: bug

#484 Prepare to eventually remove `ChildNameGenerator#CHILD_NAME_FILE`
  src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java
Labels: developer

#485 Migrate from `RestartableJenkinsRule` to `JenkinsSessionRule`
  src/test/java/com/cloudbees/hudson/plugins/folder/ChildNameGeneratorAltTest.java
  src/test/java/com/cloudbees/hudson/plugins/folder/ChildNameGeneratorRecTest.java
  src/test/java/com/cloudbees/hudson/plugins/folder/ChildNameGeneratorTest.java
  src/test/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder2Test.java
Labels: tests

#487 Prepare for eventual removal of `ChildNameGenerator#ensureItemDirectory`
  src/main/java/com/cloudbees/hudson/plugins/folder/ChildNameGenerator.java
Labels: developer

#491 Remove useless annotation
  src/main/java/com/cloudbees/hudson/plugins/folder/computed/FolderComputation.java
Labels: internal
